MUD Integration V2
ChainSafe/web3.unity pull request #1078
Opened 2024-08-05 15:59 UTC by oleksandrchainsafe

2024-08-05 20:13 UTC, juans-chainsafe requested changes
@oleksandrchainsafe I see new build errors now:
```
/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Resources/TestContract.cs(3,28): error CS0234: The type or namespace name 'Transactions' does not exist in the namespace 'ChainSafe.Gaming.Evm' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Resources/TestContract.cs(4,17): error CS0234: The type or namespace name 'Hex' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Resources/TestContract.cs(7,17): error CS0234: The type or namespace name 'RPC' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Resources/TestContract.cs(8,17): error CS0234: The type or namespace name 'JsonRpc' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Resources/TestContract.cs(9,17): error CS0234: The type or namespace name 'ABI' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Resources/TestContract.cs(10,17): error CS0234: The type or namespace name 'Contracts' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/ConnectionProvider.cs(3,29): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'ChainSafe.Gaming.Web3' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs(3,28): error CS0234: The type or namespace name 'JsonRpc' does not exist in the namespace 'ChainSafe.Gaming.Evm' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs(4,36): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'ChainSafe.Gaming.Marketplace' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs(5,24): error CS0234: The type or namespace name 'MultiCall' does not exist in the namespace 'ChainSafe.Gaming' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs(7,29): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'ChainSafe.Gaming.Web3' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs(9,17): error CS0234: The type or namespace name 'GamingSdk' does not exist in the namespace 'ChainSafe' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IWeb3BuilderServiceAdapter.cs(1,29): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'ChainSafe.Gaming.Web3' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/MetamaskConnectionProvider.cs(6,29): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'ChainSafe.Gaming.Web3' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/WalletConnectConnectionProvider.cs(3,29): error CS0234: The type or namespace name 'Build' does not exist in the namespace 'ChainSafe.Gaming.Web3' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/WalletConnectConnectionProvider.cs(4,29): error CS0234: The type or namespace name 'Evm' does not exist in the namespace 'ChainSafe.Gaming.Web3' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/CountlyAnalytics.cs(3,29): error CS0234: The type or namespace name 'Analytics' does not exist in the namespace 'ChainSafe.Gaming.Web3' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Erc1155UnityExtensions.cs(4,38): error CS0234: The type or namespace name 'BuiltIn' does not exist in the namespace 'ChainSafe.Gaming.Evm.Contracts' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Erc1155UnityExtensions.cs(5,24): error CS0234: The type or namespace name 'Ipfs' does not exist in the namespace 'ChainSafe.Gaming' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Evm.cs(7,28): error CS0234: The type or namespace name 'Providers' does not exist in the namespace 'ChainSafe.Gaming.Evm' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Evm.cs(8,28): error CS0234: The type or namespace name 'Transactions' does not exist in the namespace 'ChainSafe.Gaming.Evm' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Evm.cs(11,17): error CS0234: The type or namespace name 'Hex' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Evm.cs(12,17): error CS0234: The type or namespace name 'Hex' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Evm.cs(13,17): error CS0234: The type or namespace name 'Signer' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Evm.cs(14,17): error CS0234: The type or namespace name 'Util' does not exist in the namespace 'Nethereum' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Samples/GelatoSample.cs(4,17): error CS0234: The type or namespace name 'GamingSdk' does not exist in the namespace 'ChainSafe' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Samples/GelatoSample.cs(5,17): error CS0234: The type or namespace name 'GamingSdk' does not exist in the namespace 'ChainSafe' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Samples/MultiCallSample.cs(4,24): error CS0234: The type or namespace name 'MultiCall' does not exist in the namespace 'ChainSafe.Gaming' (are you missing an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Script [...]

2024-08-06 09:25 UTC, kantagara commented on Packages/io.chainsafe.web3-unity/Runtime/Resources/ABIContractClassTemplate.txt
> +        public string Address => OriginalContract.Address;
Noice

2024-08-06 09:35 UTC, kantagara approved these changes

2024-08-06 09:43 UTC, sneakzttv approved these changes

2024-08-06 12:17 UTC, juans-chainsafe requested changes
Errors still there

2024-08-06 15:37 UTC, juans-chainsafe approved these changes
Changes will be tested in v3 PR, there are no build errors and webgl is working.

2024-08-06 15:50 UTC, juans-chainsafe commented
> Changes will be tested in v3 PR, there are no build errors and webgl is working.

I manage to test the changes here and they are working!

2024-08-06 16:14 UTC, juans-chainsafe approved these changes

2024-08-06 16:41 UTC, merged