small fix for abi generation issues
ChainSafe/web3.unity pull request #1079
Opened 2024-08-06 08:49 UTC by kantagara

2024-08-06 09:44 UTC, sneakzttv commented
much cleaner

2024-08-06 09:44 UTC, sneakzttv approved these changes

2024-08-06 12:22 UTC, juans-chainsafe requested changes
Same build errors that I get in https://github.com/ChainSafe/web3.unity/pull/1080#pullrequestreview-2221139156

But I dont get them on https://github.com/ChainSafe/web3.unity/pull/1068

2024-08-07 10:05 UTC, oleksandrchainsafe approved these changes

2024-08-07 10:18 UTC, rob1997 approved these changes

2024-08-07 12:41 UTC, merged