Marketplace ux improvement
ChainSafe/web3.unity pull request #1105
Opened 2024-08-20 19:50 UTC by sneakzttv

Changed item population voids to tasks and awaited them for a better UX.
Fixed image issue with minting collection NFTs, endpoint needed updating.
It's a little hacky for now, will update once Arun has normalized the endpoint.

Closes #1101

To Test:
Add the marketplace prefab to a new scene and direct the login scene to it.
Login in with your dashboard email and wallet.
Load collections and marketplaces.

Expected results:
Images and data load fully before the processing menu toggles off.
NFTs can be minted to collections.

2024-08-21 13:39 UTC, juans-chainsafe requested changes
Some feedback:

- Images and data load fully before the processing menu toggles off ✅ working as expected!
- Mint NFTs ❌ 
I can't mint NFTs, I have 2 different issues:
With **ERC721** I get the CID, for example: bafyjvzacdivp5docm2pph4neizd3bk4fuwj4bqflex234qyrozpa but I don't get any popup to accept the tx to mint the NFT in Metamask. I waited 10 minutes.

With **ERC1155** I have this error:
```
Error: Cannot create a multipart form data section without body data
UnityEngine.Debug:LogError (object)
Scripts.EVM.Marketplace.Marketplace/<Mint1155CollectionNft>d__13:MoveNext () (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs:353)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<byte[]>:SetResult (byte[])
UploadPlatforms/<GetImageData>d__3:MoveNext () (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/IPFS/UploadPlatforms.cs:45)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<byte[]>:SetResult (byte[])
UploadPlatforms/<UploadImageEditor>d__4:MoveNext () (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/IPFS/UploadPlatforms.cs:57)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
IEnumeratorAwaitExtensions:RunOnUnityScheduler (System.Action)
IEnumeratorAwaitExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception)
IEnumeratorAwaitExtensions/InstructionWrappers/<ReturnSelf>d__2`1<UnityEngine.AsyncOperation>:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)
```

- There is also a 3rd error for ERC721 or ERC1155 when you put the NFT supply manually:

```
Error: The value could not be parsed.
UnityEngine.Debug:LogError (object)
Scripts.EVM.Marketplace.Marketplace/<Mint1155CollectionNft>d__13:MoveNext () (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs:353)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<string>:SetResult (string)
Scripts.EVM.Remote.CSServer/<CreateData>d__4:MoveNext () (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Remote/CSServer.cs:112)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
IEnumeratorAwaitExtensions:RunOnUnityScheduler (System.Action)
IEnumeratorAwaitExtensions/SimpleCoroutineAwaiter`1<UnityEngine.AsyncOperation>:Complete (UnityEngine.AsyncOperation,System.Exception)
IEnumeratorAwaitExtensions/InstructionWrappers/<ReturnSelf>d__2`1<UnityEngine.AsyncOperation>:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)
```

Some nice to have:

- NFT Description should not be mandatory, is optional, you can have a NFT without description
- the NFT type, when you are minting a new NFT, should not be editable, because it will always be the type of the collection, you can’t mint a 721 in a 1155 collection

2024-08-21 22:01 UTC, sneakzttv commented
You should just be able to leave the description blank

2024-08-22 08:58 UTC, sneakzttv commented
![image](https://github.com/user-attachments/assets/13a52640-077b-44f2-9373-01352976fcf1)

Type selection removed, is now passed down through the function.
NFT blank description should be ok now. Forgot to add that to the mint.
Disabled amount input when 721 collections are selected, also make sure you have that amount available in the collection etc.
Fixed mint issues. Please check and let me know when you can. We'll get through the great wall of Juan XD almost there!

2024-08-22 17:09 UTC, juans-chainsafe requested changes
New error when I click the UPLOAD IMAGE button:
```
Exception: Type not valid: 
ChainSafe.Gaming.Marketplace.MintCollectionNftManager.UploadNftImage () (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/MintCollectionNftManager.cs:49)
ChainSafe.Gaming.Marketplace.EventManagerMarketplace.RaiseMintNftToCollection () (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/EventManagerMarketplace.cs:171)
ChainSafe.Gaming.Marketplace.MarketplaceGUIManager.MintNftToCollection () (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/MarketplaceGUIManager.cs:220)
UnityEngine.Events.InvokableCall.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/UnityEvent/UnityEvent.cs:178)
UnityEngine.Events.UnityEvent.Invoke () (at /Users/bokken/build/output/unity/unity/artifacts/generated/UnityEvent/UnityEvent_0.cs:57)
UnityEngine.UI.Button.Press () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)

```
<img width="652" alt="Screenshot 2024-08-22 at 2 08 42 PM" src="https://github.com/user-attachments/assets/169759e6-2ec4-4dfd-95b5-02ebbe6bcda2">

2024-08-22 19:30 UTC, sneakzttv commented
ok try again please @juans-chainsafe

2024-08-23 11:52 UTC, sneakzttv commented
Most issues fixed, creating a new issue here for the request problem we're seeing so i can attend to it when im back. https://github.com/ChainSafe/web3.unity/issues/1107

2024-08-23 12:50 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs
> +                Debug.Log($"CID: {collectionData.cid}");
we can remove this debug

2024-08-23 12:53 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs
>              catch (Web3Exception e)
you can replace this with
```
catch (Exception e)
{
if (!(e is Web3Exception))
{
Debug.LogError("Error: " + e.Message);
}
throw e;
}

2024-08-23 12:53 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs
> +                Debug.Log($"Amount3: {amount}");
this debug can be removed

2024-08-23 12:54 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs
>              catch (Web3Exception e)
this can also be replaced with my suggestion above

2024-08-23 12:55 UTC, rob1997 commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/BrowseCollectionManager.cs
> -        private enum CollectionType
did you convert these enums into text? if so great work!

2024-08-23 12:55 UTC, rob1997 commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/BrowseCollectionManager.cs
> -        private enum CollectionType
we don't want to add new enums in the future

2024-08-23 12:56 UTC, rob1997 commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/CreateCollectionManager.cs
> +                        Debug.Log($"Web3 exception: {web3Ex}");
`LogError` here too

2024-08-23 14:00 UTC, juans-chainsafe approved these changes
Thanks Sneakz for creating a new issue with the remaining stuff. Other issues were fixed.

2024-08-26 00:17 UTC, merged