Custom Editor for Adding and removing Connection providers
ChainSafe/web3.unity pull request #1114
Opened 2024-08-27 12:28 UTC by rob1997

![image](https://github.com/user-attachments/assets/45edbddd-5b1e-4669-9e86-44c1f680ba17)

2024-08-27 12:32 UTC, kantagara approved these changes
Very nice!

2024-08-27 15:34 UTC, juans-chainsafe requested changes
Getting this error after I remove and add back again the provider. The error happens when I click play in the editor:
```
ArgumentException: The Object you want to instantiate is null.
UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Transform parent, System.Boolean instantiateInWorldSpace) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:382)
UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent, System.Boolean worldPositionStays) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:412)
UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:407)
ChainSafe.Gaming.UnityPackage.UI.ConnectModal.Initialize (ChainSafe.Gaming.UnityPackage.Connection.ConnectionHandler connectionHandler) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:43)
ConnectToWallet.Start () (at Assets/Samples/web3.unity SDK/2.6.0/Web3.Unity Samples/Scripts/Scenes/ConnectToWallet.cs:45)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

2024-08-27 19:11 UTC, rob1997 commented
> Getting this error after I remove and add back again the provider. The error happens when I click play in the editor:
> 
> ```
> ArgumentException: The Object you want to instantiate is null.
> UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Transform parent, System.Boolean instantiateInWorldSpace) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:382)
> UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent, System.Boolean worldPositionStays) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:412)
> UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:407)
> ChainSafe.Gaming.UnityPackage.UI.ConnectModal.Initialize (ChainSafe.Gaming.UnityPackage.Connection.ConnectionHandler connectionHandler) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:43)
> ConnectToWallet.Start () (at Assets/Samples/web3.unity SDK/2.6.0/Web3.Unity Samples/Scripts/Scenes/ConnectToWallet.cs:45)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
> UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
> ```

Hey Juan, the issue you're having is actually expected because removing and adding a new provider means it's new and it loses old references, the idea for add-provider is to create the connection provider but user will still need to configure it with preferred settings and references, so until you do so the references remain empty/null so if you try and run it without setting it up it'll throw an exception.

2024-08-27 19:18 UTC, juans-chainsafe approved these changes
Got it, in that case is working as expected!

2024-08-28 15:02 UTC, oleksandrchainsafe requested changes
Left a couple of discussion points.

2024-08-28 15:25 UTC, creeppak commented on Packages/io.chainsafe.web3-unity/Editor/ConnectionHandlerEditor.cs
> +            List<ConnectionProvider> availableProviders = new List<ConnectionProvider>();
I know it's just an editor window, but this stuff may cause lags in playmode, so we better keep the update loop clean.

2024-08-29 13:48 UTC, merged