Throwing an exception with a different message when there is an HTTP Connection Error
ChainSafe/web3.unity pull request #1121
Opened 2024-09-03 14:32 UTC by creeppak

When the result type of UnityWebRequest is `ConnectionError` the `request.downloadHandler.text` is empty. This makes the message in console look like this `HTTP.POST to http://127.0.0.1:8545/ responded with error:`.

This PR sets a correct message into the exception to be displayed in the console when there is a connection error

2024-09-03 16:20 UTC, kantagara approved these changes

2024-09-03 17:25 UTC, rob1997 approved these changes

2024-09-03 18:49 UTC, juans-chainsafe requested changes
I don't see the change, I see the same message as before when, for example, I try to login with HyperPlay but HyperPlay is not opened:
```
Web3Exception: HTTP.POST to 'http://localhost:9680/rpc' - connection error.
ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient.UnityWebRequestToNetworkResponse (UnityEngine.Networking.UnityWebRequest request) (at <7ff2334a7c81478492adaa4750c49874>:0)
ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient+<>c__DisplayClass4_0.<PostRaw>b__0 () (at <7ff2334a7c81478492adaa4750c49874>:0)
ChainSafe.Gaming.Evm.Unity.Dispatcher+<>c__DisplayClass12_0`1[T].<EnqueueTask>g__WrappedAction|0 () (at <857c20de9ea546f7a6da445fef65e940>:0)
ChainSafe.Gaming.HyperPlay.HyperPlayProvider.Request[T] (System.String method, System.Object[] parameters) (at <f3e548180e5242888fb6baddf704d0f6>:0)
ChainSafe.Gaming.HyperPlay.HyperPlayProvider.Connect () (at <f3e548180e5242888fb6baddf704d0f6>:0)
ChainSafe.Gaming.Web3.Evm.Wallet.WalletSigner.WillStartAsync () (at <614998690b3d4f908489da1fd3474277>:0)
ChainSafe.Gaming.Web3.Web3.InitializeAsync () (at <614998690b3d4f908489da1fd3474277>:0)
ChainSafe.Gaming.Web3.Build.Web3Builder.LaunchAsync () (at <614998690b3d4f908489da1fd3474277>:0)
ChainSafe.Gaming.UnityPackage.Connection.IConnectionHandler.Connect (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs:42)
ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider.HandleException (System.Exception exception) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/ConnectionProvider.cs:47)
ChainSafe.Gaming.UnityPackage.UI.ConnectModal.TryConnect (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:81)
ChainSafe.Gaming.UnityPackage.UI.ConnectModal.<Initialize>g__ConnectClicked|10_0 (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:57)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <606c2e0a56af495988c860a4ac613e74>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

```

2024-09-04 10:07 UTC, creeppak commented
> I don't see the change, I see the same message as before when, for example, I try to login with HyperPlay but HyperPlay is not opened:
> 
> ```
> Web3Exception: HTTP.POST to 'http://localhost:9680/rpc' - connection error.
> ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient.UnityWebRequestToNetworkResponse (UnityEngine.Networking.UnityWebRequest request) (at <7ff2334a7c81478492adaa4750c49874>:0)
> ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient+<>c__DisplayClass4_0.<PostRaw>b__0 () (at <7ff2334a7c81478492adaa4750c49874>:0)
> ChainSafe.Gaming.Evm.Unity.Dispatcher+<>c__DisplayClass12_0`1[T].<EnqueueTask>g__WrappedAction|0 () (at <857c20de9ea546f7a6da445fef65e940>:0)
> ChainSafe.Gaming.HyperPlay.HyperPlayProvider.Request[T] (System.String method, System.Object[] parameters) (at <f3e548180e5242888fb6baddf704d0f6>:0)
> ChainSafe.Gaming.HyperPlay.HyperPlayProvider.Connect () (at <f3e548180e5242888fb6baddf704d0f6>:0)
> ChainSafe.Gaming.Web3.Evm.Wallet.WalletSigner.WillStartAsync () (at <614998690b3d4f908489da1fd3474277>:0)
> ChainSafe.Gaming.Web3.Web3.InitializeAsync () (at <614998690b3d4f908489da1fd3474277>:0)
> ChainSafe.Gaming.Web3.Build.Web3Builder.LaunchAsync () (at <614998690b3d4f908489da1fd3474277>:0)
> ChainSafe.Gaming.UnityPackage.Connection.IConnectionHandler.Connect (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs:42)
> ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider.HandleException (System.Exception exception) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/ConnectionProvider.cs:47)
> ChainSafe.Gaming.UnityPackage.UI.ConnectModal.TryConnect (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:81)
> ChainSafe.Gaming.UnityPackage.UI.ConnectModal.<Initialize>g__ConnectClicked|10_0 (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:57)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <606c2e0a56af495988c860a4ac613e74>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
> UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
> ```

It's a different message actually :D

Now it says `Web3Exception: HTTP.POST to 'http://localhost:9680/rpc' - connection error.` in your console output sample. Notice the 'connection error', before it was 'responded with error:' (no error provided after the ':').

2024-09-04 12:06 UTC, juans-chainsafe commented
> > I don't see the change, I see the same message as before when, for example, I try to login with HyperPlay but HyperPlay is not opened:
> > ```
> > Web3Exception: HTTP.POST to 'http://localhost:9680/rpc' - connection error.
> > ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient.UnityWebRequestToNetworkResponse (UnityEngine.Networking.UnityWebRequest request) (at <7ff2334a7c81478492adaa4750c49874>:0)
> > ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient+<>c__DisplayClass4_0.<PostRaw>b__0 () (at <7ff2334a7c81478492adaa4750c49874>:0)
> > ChainSafe.Gaming.Evm.Unity.Dispatcher+<>c__DisplayClass12_0`1[T].<EnqueueTask>g__WrappedAction|0 () (at <857c20de9ea546f7a6da445fef65e940>:0)
> > ChainSafe.Gaming.HyperPlay.HyperPlayProvider.Request[T] (System.String method, System.Object[] parameters) (at <f3e548180e5242888fb6baddf704d0f6>:0)
> > ChainSafe.Gaming.HyperPlay.HyperPlayProvider.Connect () (at <f3e548180e5242888fb6baddf704d0f6>:0)
> > ChainSafe.Gaming.Web3.Evm.Wallet.WalletSigner.WillStartAsync () (at <614998690b3d4f908489da1fd3474277>:0)
> > ChainSafe.Gaming.Web3.Web3.InitializeAsync () (at <614998690b3d4f908489da1fd3474277>:0)
> > ChainSafe.Gaming.Web3.Build.Web3Builder.LaunchAsync () (at <614998690b3d4f908489da1fd3474277>:0)
> > ChainSafe.Gaming.UnityPackage.Connection.IConnectionHandler.Connect (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs:42)
> > ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider.HandleException (System.Exception exception) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/ConnectionProvider.cs:47)
> > ChainSafe.Gaming.UnityPackage.UI.ConnectModal.TryConnect (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:81)
> > ChainSafe.Gaming.UnityPackage.UI.ConnectModal.<Initialize>g__ConnectClicked|10_0 (ChainSafe.Gaming.UnityPackage.Connection.ConnectionProvider provider) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/UI/ConnectModal.cs:57)
> > System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <606c2e0a56af495988c860a4ac613e74>:0)
> > UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
> > UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
> > UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
> > ```
> 
> It's a different message actually :D
> 
> Now it says `Web3Exception: HTTP.POST to 'http://localhost:9680/rpc' - connection error.` in your console output sample. Notice the 'connection error', before it was 'responded with error:' (no error provided after the ':').

My bad! I though the full message was changing. Approving it.

2024-09-04 12:06 UTC, juans-chainsafe approved these changes

2024-09-05 08:06 UTC, merged