Chain Switching V2
ChainSafe/web3.unity pull request #1134
Opened 2024-09-10 13:00 UTC by creeppak

2024-09-13 13:54 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity/Runtime/Scripts/ProjectConfigAsset.cs
> +    public class ProjectConfigAsset : ScriptableObject, ICompleteProjectConfig
Maybe we wanna rename this to Web3Config inline with the file rename?

2024-09-13 14:09 UTC, rob1997 commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.6.0/Web3.Unity Samples/Scenes/SampleMain.unity
are the changes here necessary, asking because it'll cause a conflict with my PR

2024-09-13 14:09 UTC, rob1997 commented on src/ChainSafe.Gaming/Web3/Evm/Wallet/WalletProvider.cs
> +                await Request<string>("wallet_switchEthereumChain", networkSwitchParams);
🔥

2024-09-13 14:10 UTC, rob1997 approved these changes

2024-09-13 15:14 UTC, kantagara approved these changes

2024-09-13 15:19 UTC, juans-chainsafe requested changes
I have the following build error:

`/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Editor/Web3SettingsEditor.cs(260,17): error CS0103: The name 'WriteNetworkFile' does not exist in the current context`

2024-09-13 16:27 UTC, juans-chainsafe requested changes
Build error fixed.
Now Im getting a build error when building on WebGL:
`/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.hyperplay/Runtime/Scripts/HyperPlayWebGLProvider.cs(34,215): error CS1729: 'HyperPlayProvider' does not contain a constructor that takes 6 arguments`

2024-09-13 16:35 UTC, juans-chainsafe commented
> Build error fixed. Now Im getting a build error when building on WebGL: `/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.hyperplay/Runtime/Scripts/HyperPlayWebGLProvider.cs(34,215): error CS1729: 'HyperPlayProvider' does not contain a constructor that takes 6 arguments`

In editor, Im getting this error when trying the "Toggle Chain" sample:
```
Web3Exception: No IChainConfig was registered with id '11155420'. Make sure to configure settings for the provided chain before switching to it.
ChainSafe.Gaming.Web3.Core.Chains.ChainManager.SwitchChain (System.String newChainId) (at <ea882f203ba344a0867ecd05a000a963>:0)
Samples.Behaviours.SwitchChain.SwitchChainCalls.ToggleChain () (at Assets/Samples/web3.unity SDK/2.6.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/SwitchChain/SwitchChainCalls.cs:22)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <606c2e0a56af495988c860a4ac613e74>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

2024-09-14 09:08 UTC, creeppak commented on Packages/io.chainsafe.web3-unity/Runtime/Scripts/Connection/IConnectionHandler.cs
> +                // .UseMultiCall()
there is an error when initializing Multicall for Optimism Sepolia (2nd test chain for samples). I was thinking you removed its usage from the SampleMain scene, but I should probably fix this anyways.. working on it

2024-09-14 09:10 UTC, creeppak commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.6.0/Web3.Unity Samples/Scenes/SampleMain.unity
yeah, they are. There is a new "*Calls" sampel script object and and a panel "Switch Chain". Duplicating the scene before megre and copying this into a new scene should work just fine.

2024-09-14 10:36 UTC, merged