Updating Countly to the latest version and supressing bunch of the warnings coming from it.
ChainSafe/web3.unity pull request #1251
Opened 2024-12-04 07:33 UTC by kantagara

This should close #1237 #1221

2024-12-04 07:34 UTC, kantagara commented on Packages/io.chainsafe.web3-unity/Runtime/Libraries/ChainSafe.Gaming.WalletConnect.dll.meta
IDK Why these were here in the first place TBH

2024-12-04 07:35 UTC, kantagara commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/3.0.6/Web3.Unity Samples/Scripts/Samples/EvmSample.cs
it was complaining that some fields aren't used at all. :D

2024-12-04 08:06 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity/Runtime/Libraries/ChainSafe.Gaming.WalletConnect.dll.meta
We should keep these, some dlls are platform specific, like EthereumWindow for WebGL

2024-12-04 08:07 UTC, rob1997 commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/3.0.6/Web3.Unity Samples/Scripts/Samples/EvmSample.cs
Can't we remove the fields?

2024-12-04 08:08 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity/Runtime/Libraries/ChainSafe.Gaming.WalletConnect.dll.meta
oh right, Wc -> Reown, my bad 🤦

2024-12-04 08:19 UTC, kantagara commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/3.0.6/Web3.Unity Samples/Scripts/Samples/EvmSample.cs
Yeah you are right, removed them!

2024-12-04 08:31 UTC, sneakzttv approved these changes

2024-12-05 10:26 UTC, rob1997 approved these changes

2024-12-06 17:47 UTC, juans-chainsafe requested changes
New events are displayed if you are trying in WebGL, but no 1 single event is displayed when I try from the editor.

Also, new user profiles are not displayed/created.

2024-12-11 16:13 UTC, creeppak approved these changes

2025-12-11 07:35 UTC, closed without merging