Ethers core
ChainSafe/web3.unity pull request #335
Opened 2023-02-18 06:13 UTC by KBryan

2023-02-19 08:43 UTC, sneakzttv approved these changes
core dll woo

2023-02-20 21:02 UTC, FSM1 requested changes
A couple of files made it in to the repo that I think don't necessarily have to be there.

2023-02-20 21:02 UTC, FSM1 commented on Scenes/SampleScene.unity
> +%YAML 1.1
Any reason this is being added to the repo?

2023-02-20 21:02 UTC, FSM1 commented on Resources/BillingMode.json
> +{"androidStore":"GooglePlay"}
Same here

2023-02-20 21:02 UTC, FSM1 commented on Resources/BillingMode.json
> +{"androidStore":"GooglePlay"}
Same here

2023-02-20 21:02 UTC, FSM1 commented on Resources/BillingMode.json
> +{"androidStore":"GooglePlay"}
Any reason this is being added to the repo?

2023-02-21 16:43 UTC, sneakzttv approved these changes

2023-02-21 16:47 UTC, merged