Added checks if wallet is present
ChainSafe/web3.unity pull request #568
Opened 2023-08-23 11:21 UTC by RyRy79261

closes #524

2023-08-23 11:31 UTC, kalambet submitted a review, later dismissed
LGTM

2023-08-23 12:24 UTC, sneakzttv commented
#545 is related here, just check that also

2023-08-23 14:13 UTC, oleksandrchainsafe commented
Shouldn't we show some kind of warning popup if there is no wallet installed?

2023-08-23 15:02 UTC, juans-chainsafe commented
> Shouldn't we show some kind of warning popup if there is no wallet installed?

@RyRy79261 agree, maybe something like when you cancel the login transaction in the wallet and in the LoginScene appears a red message saying "Login failed"

2023-08-23 15:45 UTC, sneakzttv commented
1 version would be nice but afaik unity needs that to run javascript as it has no environment to run in without a browser which is why we're using the api instead. We're not actually using the browser, we're just opening a link and making a post request and then copying the data back into unity via clipboard.

```
public static async Task<string> Sign(string _message)
    {
        // open application
        string message = Uri.EscapeDataString(_message);
        Application.OpenURL(url + "?action=sign" + "&message=" + message);
        // set clipboard to empty
        GUIUtility.systemCopyBuffer = "";
        // wait for clipboard response
        string clipBoard = "";
        while (clipBoard == "")
        {
            clipBoard = GUIUtility.systemCopyBuffer;
            await Task.Delay(100);
        }
        // check if clipboard response is valid
        if (clipBoard.StartsWith("0x") && clipBoard.Length == 132)
        {
            return clipBoard;
        }
        else
        {
            throw new Exception("sign error");
        }   
    }
```

Interested to see how we go about this.

2023-08-24 12:47 UTC, RyRy79261 commented
@kalambet @oleksandrchainsafe @sneakzttv @juans-chainsafe 

So what is the status here, create a pop up if no wallet present, continue, nuke it or what is requested?

2023-08-29 09:33 UTC, kalambet commented
> So what is the status here, create a pop up if no wallet present, continue, nuke it or what is requested?

@RyRy79261 let's do some minimal notification, like `alert` or something similar and this is it.

2023-08-30 16:02 UTC, sneakzttv submitted a review, later dismissed

2023-08-30 20:20 UTC, sneakzttv submitted a review, later dismissed

2023-08-30 20:24 UTC, kalambet requested changes
@RyRy79261 let's do some minimal notification, like alert or something similar and this is it.

2023-08-31 11:09 UTC, sneakzttv commented
testing

2023-08-31 11:12 UTC, sneakzttv commented
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/1f5c654d-9d80-44d2-b498-71e69f9ee33a)
 launch errors, the previous pr should fix this, will check again after rob confirms and we merge

2023-08-31 11:18 UTC, robGG1997 submitted a review, later dismissed

2023-09-01 15:22 UTC, sneakzttv requested changes
Code cleanup for wait for seconds RE above, if the current code was intentional just dismiss my changes <3

2023-09-04 17:13 UTC, RyRy79261 commented
Ahoy

So what I've done is for 2020x I've left Onboard to load as it just displays the options available (Torus & WalletConnect) For Metamask template, it just pops up the alert

2023-09-04 19:29 UTC, sneakzttv commented
![image](https://github.com/ChainSafe/web3.unity/assets/57473220/2959a9f6-e595-450c-bd47-36450d6c2888)

Alert working, just getting clarification from Ry on the built in duplication method before approving

2023-09-04 19:41 UTC, sneakzttv submitted a review, later dismissed
lgtm

2023-09-05 12:20 UTC, oleksandrchainsafe requested changes

2023-09-05 12:20 UTC, oleksandrchainsafe commented on src/UnitySampleProject/Assets/Scripts/Samples/GelatoSample.cs
> +using UnityEngine;
I think this can be reverted.

2023-09-05 12:28 UTC, sneakzttv approved these changes

2023-09-05 12:32 UTC, juans-chainsafe approved these changes
Working great!

WebGL - 2020x template:
<img width="846" alt="Screenshot 2023-09-05 at 09 28 52" src="https://github.com/ChainSafe/web3.unity/assets/104365141/924cc7b6-a593-4eb1-b6e0-fcfc2acfc3c2">

WebGL - Metamask template:
<img width="452" alt="Screenshot 2023-09-05 at 09 32 10" src="https://github.com/ChainSafe/web3.unity/assets/104365141/c1cec53f-8be7-4d4d-8be6-b80ffd28316d">

I also tested if still working with Metamask being installed

2023-09-06 11:03 UTC, oleksandrchainsafe approved these changes

2023-09-07 12:47 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity/Runtime/Libraries/ChainSafe.GamingSDK.EVM.WebPageWallet.pdb.meta
@robGG1997 Tbh I am not sure, Unity generates them, maybe @oleksandrchainsafe or @kantagara knows

2023-09-07 12:50 UTC, kantagara commented on src/UnityPackages/io.chainsafe.web3-unity/Runtime/Libraries/ChainSafe.GamingSDK.EVM.WebPageWallet.pdb.meta
if something is in the Assets folder, no matter what extension it has it will always add meta files, so if some file gets deleted and replaced with a new one, the new one will also get it's own meta file.

2023-09-07 16:00 UTC, kalambet approved these changes

2023-09-07 16:00 UTC, merged