Erc20 Unit Tests
ChainSafe/web3.unity pull request #607
Opened 2023-09-11 13:29 UTC by kantagara

2023-09-11 16:05 UTC, juans-chainsafe reviewed
I dont get those errors anymore, and tests are working locally!
<img width="304" alt="Screenshot 2023-09-11 at 13 04 05" src="https://github.com/ChainSafe/web3.unity/assets/104365141/22c07590-d55b-452e-9f1c-36788a321d78">

But I get all these errors if I try to build with WebGL:
```
Assets/Tests/Erc20Tests.cs(16,6): error CS0246: The type or namespace name 'UnitySetUpAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(16,6): error CS0246: The type or namespace name 'UnitySetUp' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(36,6): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(36,6): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(48,6): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(48,6): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(57,6): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(57,6): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(66,6): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(66,6): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(80,6): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(80,6): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(90,6): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(90,6): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

Error building Player because scripts had compiler errors

Build completed with a result of 'Failed' in 5 seconds (5247 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)

UnityEditor.BuildPlayerWindow+BuildMethodException: 15 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ce] in /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPlayerWindowBuildMethods.cs:193 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPlayerWindowBuildMethods.cs:94 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)
```
@kantagara

2023-09-11 17:30 UTC, juans-chainsafe submitted a review, later dismissed
Errors fixed

2023-09-11 18:27 UTC, sneakzttv commented
linter is failing, whitespaces :D

2023-09-11 18:29 UTC, sneakzttv approved these changes

2023-09-11 21:58 UTC, robGG1997 requested changes

2023-09-11 21:58 UTC, robGG1997 commented on src/ChainSafe.GamingSdk.EVM.Unity/publish-to-unity-package.sh
is this change necessary? `setup.sh` uses this bash script we shouldn't change it unless we need to

2023-09-11 21:58 UTC, robGG1997 commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0-pre001/Web3.Unity Samples/Scripts/Editor/Tests.meta
could we update the hierarchy/directory for tests based on [this](https://docs.unity3d.com/Manual/cus-tests.html), which should fix the namespace build errors, you can also merge to #603 and work from there

2023-09-12 09:11 UTC, kalambet commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0-pre001/Web3.Unity Samples/Scripts/Editor/Tests.meta
Yes, 603 should be merged first, I agree.

2023-09-12 09:16 UTC, kalambet commented on src/ChainSafe.GamingSdk.EVM.Unity/publish-to-unity-package.sh
Yes, running `setup.sh` every time include unnecessary git submodules initialization. So after all the source changes in order to re-publish built sources I'm using both `publish-to-unity-package.sh` and `debug-publish-to-unity-package.sh`

2023-09-12 09:34 UTC, robGG1997 commented on src/ChainSafe.GamingSdk.EVM.Unity/publish-to-unity-package.sh
understood

2023-09-12 11:04 UTC, sneakzttv commented
play mode failing

2023-09-12 12:17 UTC, robGG1997 commented
LGTM
![image](https://github.com/ChainSafe/web3.unity/assets/142783680/fb09ee68-59cb-4273-bacf-4c344fa1fcce)

2023-09-12 12:18 UTC, robGG1997 approved these changes

2023-09-12 12:20 UTC, juans-chainsafe approved these changes
Looks good! playmode working again as well.

WebGL working as well

2023-09-12 12:44 UTC, RyRy79261 approved these changes
Tested in unity code looks good

2023-09-12 12:50 UTC, merged