WebGL Web3Auth Login Nikola's fix
ChainSafe/web3.unity pull request #608
Opened 2023-09-11 13:48 UTC by kalambet

Closes #553

2023-09-11 14:00 UTC, kantagara commented
@kalambet 
![image](https://github.com/ChainSafe/web3.unity/assets/8202013/04c047b2-2731-4a7a-9663-1fe181238e19)
We need these three as well.

2023-09-11 14:17 UTC, kantagara commented
@kalambet they're in.

2023-09-12 10:39 UTC, RyRy79261 requested changes

2023-09-12 10:39 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Web3Auth.cs
> +        Debug.Log($"Session check is: {!string.IsNullOrEmpty(sessionId)}");
We can likely remove these
```suggestion
```

2023-09-12 10:39 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Web3Auth.cs
> +        Debug.Log($"in auth check {sessionId}");
We can likely remove these
```suggestion
```

2023-09-12 10:39 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Web3Auth.cs
> +                                Debug.Log("Coroutine logout result not null");
We can likely remove these
```suggestion
```

2023-09-12 10:39 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Web3Auth.cs
> +                                    Debug.Log("DEleted things probably");
We can likely remove these
```suggestion
```

2023-09-12 10:39 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Web3Auth.cs
> +                                    Debug.Log("Errored deleting");
We can likely remove these
```suggestion
```

2023-09-12 10:39 UTC, RyRy79261 commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0-pre001/Web3.Unity Samples/Scripts/Prefabs/Logout.cs
> +        Debug.Log("Trying the other login");
We can likely remove these
```suggestion
```

2023-09-12 10:51 UTC, kalambet commented
@RyRy79261 I would rather not touch stuff in `[Web3AuthSDK]` folder more than necessary. It is a pure import from Web3Auth repo and the less changes we have the easier it would be to merge with the upstream.

I would rather go with something like:
```csharp
 #if UNITY_EDITOR
 Debug.logger.logEnabled = true;
 #else
 Debug.logger.logEnabled = false;
 #endif
 ```

2023-09-12 11:00 UTC, RyRy79261 commented
@kalambet So those lines I mentioned are actually my debug lines I intended to remove on my branch before they were cherry picked to Nikola's fix 😅

2023-09-12 11:02 UTC, kalambet commented
Lol, I see. That make sense 🤣
Will update PR shortly!

2023-09-12 11:04 UTC, sneakzttv commented
awaiting update :D

2023-09-12 12:10 UTC, kantagara approved these changes

2023-09-12 13:54 UTC, kalambet commented
Just in case. I left Gelato 1Balance API key in the sources intentional so you can test all the buttons in a Demo Scene.

2023-09-12 13:59 UTC, RyRy79261 reviewed
Minor changes, left overs from my inprogress commits

2023-09-12 13:59 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Plugins/Web3AuthSDK/Web3Auth.cs
> +        Debug.Log($"redirectUrl: {redirectUrl} appState:{appState}");
Could remove this, one of my debug lines
```suggestion
```

2023-09-12 13:59 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Web3AuthWallet.cs
> +            string privateKeyString;
Could declare this on line 50, left over from a different logic
```suggestion
```

2023-09-12 13:59 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Web3AuthWallet.cs
> +            privateKeyString = await loginTcs.Task;
```suggestion
            var privateKeyString = await loginTcs.Task;
```

2023-09-12 13:59 UTC, RyRy79261 commented on src/UnityPackages/io.chainsafe.web3-unity.web3auth/Runtime/Web3AuthWallet.cs
> +            Debug.Log("Logging out via WillStop");
Could remove 
```suggestion
```

2023-09-12 14:11 UTC, RyRy79261 approved these changes
Tested in Webgl, works perfectly

2023-09-12 14:16 UTC, sneakzttv approved these changes

2023-09-12 19:45 UTC, juans-chainsafe approved these changes
Awesome! working on WebGL in both templates as well.

2023-09-12 20:24 UTC, merged