Wrote tests for ERC721
ChainSafe/web3.unity pull request #612
Opened 2023-09-13 14:12 UTC by RyRy79261

closes #598

2023-09-13 15:31 UTC, juans-chainsafe submitted a review, later dismissed

2023-09-13 15:31 UTC, juans-chainsafe commented on src/UnityPackages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs
> +        Assert.AreEqual(ownerOfBatchExpected[0], getOwnerOfBatch.Result[0]);
can't we use the CollectionAssert.AreEqual here?

2023-09-13 15:57 UTC, kalambet requested changes
I think @juans-chainsafe about CollectionAssert make sense

2023-09-13 16:49 UTC, kalambet approved these changes

2023-09-13 16:55 UTC, juans-chainsafe approved these changes

2023-09-14 03:02 UTC, sneakzttv approved these changes

2023-09-14 05:51 UTC, robGG1997 approved these changes

2023-09-14 06:21 UTC, kantagara approved these changes

2023-09-14 09:24 UTC, merged