Dispose of Wallet Connect instances properly
ChainSafe/web3.unity pull request #737
Opened 2023-11-16 07:36 UTC by robGG1997

closes #734

2023-11-16 12:33 UTC, juans-chainsafe requested changes
Almost there, just a small issue when you try to login again:

1. Login with wallet connect
2. Logout
3. Try to login again (click on "Continue with Existing Wallet")

```
IOException: Sharing violation on path /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/src/UnitySampleProject/Assets/walletconnect.json
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
System.IO.File.AsyncStreamWriter (System.String path, System.Text.Encoding encoding, System.Boolean append) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
System.IO.File.WriteAllTextAsync (System.String path, System.String contents, System.Text.Encoding encoding, System.Threading.CancellationToken cancellationToken) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
WalletConnectSharp.Storage.FileSystemStorage.Save () (at <d55ee49d308e4c7c864b1df5f80cf891>:0)
WalletConnectSharp.Storage.FileSystemStorage.SetItem[T] (System.String key, T value) (at <d55ee49d308e4c7c864b1df5f80cf891>:0)
WalletConnectSharp.Sign.Engine.WalletConnectSharp.Sign.Interfaces.IEnginePrivate.SetProposal (System.Int64 id, WalletConnectSharp.Sign.Models.ProposalStruct proposal) (at <c612a349c7a842b9ab87d369d96c310f>:0)
WalletConnectSharp.Sign.Engine.Connect (WalletConnectSharp.Sign.Models.Engine.ConnectOptions options) (at <c612a349c7a842b9ab87d369d96c310f>:0)
ChainSafe.Gaming.WalletConnect.WalletConnectCustomProvider.Connect () (at <0d761a7b4e8b474e9c5f91afd144ba36>:0)
ChainSafe.Gaming.WalletConnect.WalletConnectSigner.WillStartAsync () (at <0d761a7b4e8b474e9c5f91afd144ba36>:0)
ChainSafe.Gaming.Web3.Web3.InitializeAsync () (at <ba56d4ca523b4a14ac1420e44204be9d>:0)
ChainSafe.Gaming.Web3.Build.Web3Builder.LaunchAsync () (at <ba56d4ca523b4a14ac1420e44204be9d>:0)
Scenes.Login.TryLogin () (at Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/Login.cs:54)
ExistingWalletLogin.LoginClicked () (at Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/ExistingWalletLogin.cs:99)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```
<img width="828" alt="Screenshot 2023-11-16 at 09 33 45" src="https://github.com/ChainSafe/web3.unity/assets/104365141/788fe8b3-4810-4bf0-bd4d-796f3ca1fb29">

2023-11-16 13:52 UTC, juans-chainsafe approved these changes
All working now!

2023-11-17 10:28 UTC, sneakzttv approved these changes

2023-11-17 10:43 UTC, RyRy79261 approved these changes

2023-11-17 13:56 UTC, kantagara approved these changes

2023-11-17 14:09 UTC, merged