Custom networks for Multicall empty instead of null
ChainSafe/web3.unity pull request #822
Opened 2024-01-10 11:03 UTC by RyRy79261

closes #821 

For making the custom network extendable, presently, the networks are only consumed when multicall's service is initialized

2024-01-10 11:26 UTC, kantagara approved these changes

2024-01-10 13:08 UTC, kantagara approved these changes

2024-01-10 13:08 UTC, kantagara requested changes
You removed the line 36 as well, but that line should've been there.

2024-01-11 11:05 UTC, kantagara approved these changes

2024-01-11 11:11 UTC, oleksandrchainsafe approved these changes

2024-01-11 11:21 UTC, robGG1997 approved these changes

2024-01-12 06:20 UTC, sneakzttv approved these changes

2024-01-12 08:51 UTC, merged