Sygma Client implementation.
ChainSafe/web3.unity pull request #923
Opened 2024-04-12 15:38 UTC by kantagara

FINALLY sygma works. 
IT took a LOT of time to make it work.

One very very important note: I am pretty sure that for all of you the Erc1155 will fail to execute. You'd need to own some 1155 with a specific tokenId on Sepolia, and then you can test it out. Chain Id is set to Cronos.

ANOTHER NOTE:
I did update Countly on this branch by accident, so just ignore everything Countly related.

2024-04-15 06:14 UTC, boorich commented
This is great!

2024-04-15 15:03 UTC, juans-chainsafe reviewed
Some updates:
The flow is working correctly in our side right now, I tested in the editor with wallet connect in Metamask and in WebGL with Metamask login.

But there is a issue in Sygma side right now that causes the transfer to not go through.
I will test the complete flow when thats fixed.

FYI: something weird that Im not sure if is in our side or Sygma, the approve to access the tokens inside the collection should happen only once (if that collection was approved before), otherwise we are spending extra gas fees on that every time https://sepolia.etherscan.io/tx/0x9143b7d169f8c899012f66828bbe1fe7c41518dc50bd4a0d30121e7a41e3d07f

2024-04-18 15:50 UTC, juans-chainsafe approved these changes
Functionality is working if you provide the specific data to use it, but for a final user is not practical.

A final version will need:
- Approve only 1 time per collection and not in all transactions
- A log for the user to know where he can find the token in the new chain or the transaction hash in that chain
- Be able to select which tokens I want to transfer
- Should work with any ERC-1155 tokens and not only the ones that Sygma send to us

But this implementation is a big step and a great functionality to have! Congrats

2024-04-22 09:07 UTC, sneakzttv approved these changes

2024-04-22 10:45 UTC, oleksandrchainsafe requested changes
Left a couple of comments

2024-04-22 10:45 UTC, oleksandrchainsafe commented on src/ChainSafe.Gaming.SygmaClient/Contracts/BasicFeeHandler.cs
> +            contract = cb.Build(FeeHandlerAbi, address);
The FeeHandlerAbi, you can replace the huge constant declared inside the file with an embedded resource. There is an example in the Marketplace project.
There is also a helper method to read ABI from resources. It's called `AbiHelper.ReadAbiFromResources`.

2024-04-22 10:45 UTC, oleksandrchainsafe commented on src/ChainSafe.Gaming.SygmaClient/DepositDataHandlers/SemiFungibleDepositDataHandler.cs
> +    // Struct so we don't allocate memory on the heap
It's not a struct.

2024-04-22 10:45 UTC, oleksandrchainsafe commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scenes/SampleTransfer.cs
> +        await Erc20.TransferErc20(Web3Accessor.Web3, Contracts.Erc20, toAddress, System.Numerics.BigInteger.Parse(amount));
Does this sample have anything to do with the Sygma integration?

2024-04-22 10:45 UTC, oleksandrchainsafe commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/SygmaClient.cs
> +    private Web3 _web3;
We were using lowercase names without the "_" prefix for private fields before. Let's stick to one style.

2024-04-22 10:45 UTC, oleksandrchainsafe commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/SygmaClient.cs
> +public class SygmaClient : MonoBehaviour
I would recommend renaming it to avoid confusion around names. This is more like SygmaSample that Client.

2024-04-22 10:45 UTC, oleksandrchainsafe commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/SygmaClient.cs
> +public class SygmaConfig
We can move all fields right into the sample behaviour, as this is more like SygmaSampleConfig than the actual config of the SygmaClient.

2024-04-22 10:45 UTC, oleksandrchainsafe commented on src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/SygmaClient.cs
> +        _isSygmaInitialized = _sygmaClient.Initialize(sygmaConfig.SygmaEnvironment);
Shouldn't the value of SygmaEnvironment reflect the one for the original (default) chain settings from the server settings window?

2024-04-24 10:45 UTC, rob1997 reviewed
Nice work! added a few comments, mostly just questions tbh

2024-04-24 10:45 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity.lootboxes/Chainlink/Runtime/Libraries/ChainSafe.Gaming.Lootboxes.Chainlink.dll
We don't need to track these DLLs, they'll be auto committed in dev

2024-04-24 10:45 UTC, rob1997 commented on Packages/io.chainsafe.web3-unity.lootboxes/Chainlink/Runtime/Libraries/ChainSafe.Gaming.Lootboxes.Chainlink.dll
Or the DLLs in `Packages/io.chainsafe.web3-unity/Runtime/Libraries/`

2024-04-24 10:45 UTC, rob1997 commented on src/UnitySampleProject/ProjectSettings/TimelineSettings.asset
We can ignore this, right?

2024-07-22 07:24 UTC, kantagara commented
Closing this PR until we get better DevEx.

2024-07-22 07:24 UTC, closed without merging