Refine ERC20, ERC721, ERC1155 utility classes
ChainSafe/web3.unity pull request #952
Opened 2024-05-13 17:51 UTC by oleksandrchainsafe

Removed static Erc20, Erc721, Erc1155 utility classes from package scripts and added corresponding built-in contracts (ErcXXContract) and services (ErcXXService) to the core solution.

Introduced IpfsHelper.

2024-05-13 18:59 UTC, juans-chainsafe requested changes
I run the setup.sh but Im getting the following build errors:

```
Library/PackageCache/com.tools.webglthreadingpatcher@c2f3628a02/ThreadingPatcher/Editor/WebGLThreadingPatcher.cs(21,38): error CS1061: 'BuildReport' does not contain a definition for 'GetFiles' and no accessible extension method 'GetFiles' accepting a first argument of type 'BuildReport' could be found (are you missing a using directive or an assembly reference?)

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(48,28): error CS0103: The name 'Erc721' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(56,26): error CS0103: The name 'Erc721' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(64,31): error CS0103: The name 'Erc721' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(72,19): error CS0103: The name 'Erc721' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(30,28): error CS0103: The name 'Erc1155' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(38,28): error CS0103: The name 'Erc1155' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(49,19): error CS0103: The name 'Erc1155' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(139,22): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmTests.cs(110,84): error CS0103: The name 'EthMethod' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(150,23): error CS0103: The name 'Erc721' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(161,24): error CS0103: The name 'Erc1155' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(172,29): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(183,30): error CS0103: The name 'Erc721' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmTests.cs(152,34): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(194,31): error CS0103: The name 'Erc1155' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(129,23): error CS0103: The name 'Erc1155' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(30,28): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(38,34): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(46,27): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(54,23): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(62,25): error CS0103: The name 'Erc20' does not exist in the current context

/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(70,30): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(43,29): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(44,65): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(44,80): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(75,19): error CS0103: The name 'Erc1155' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(76,21): error CS0103: The name 'Erc1155' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(77,65): error CS0103: The name 'Erc1155' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(77,82): error CS0103: The name 'Erc1155' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(52,28): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(53,64): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(53,79): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(61,28): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(62,64): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(62,79): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(85,30): error CS0103: The name 'Erc1155' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(87,61): error CS0103: The name 'Erc1155' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(87,78): error CS0103: The name 'Erc1155' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(70,28): error CS0103: The name 'Erc20' does not exist in the current context

Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(71,53): error CS0103: T [...]

2024-05-13 19:00 UTC, juans-chainsafe commented
> I run the setup.sh but Im getting the following build errors:
> 
> ```
> Library/PackageCache/com.tools.webglthreadingpatcher@c2f3628a02/ThreadingPatcher/Editor/WebGLThreadingPatcher.cs(21,38): error CS1061: 'BuildReport' does not contain a definition for 'GetFiles' and no accessible extension method 'GetFiles' accepting a first argument of type 'BuildReport' could be found (are you missing a using directive or an assembly reference?)
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(48,28): error CS0103: The name 'Erc721' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(56,26): error CS0103: The name 'Erc721' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(64,31): error CS0103: The name 'Erc721' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(72,19): error CS0103: The name 'Erc721' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(30,28): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(38,28): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(49,19): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(139,22): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmTests.cs(110,84): error CS0103: The name 'EthMethod' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(150,23): error CS0103: The name 'Erc721' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(161,24): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(172,29): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(183,30): error CS0103: The name 'Erc721' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmTests.cs(152,34): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(194,31): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(129,23): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(30,28): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(38,34): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(46,27): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(54,23): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(62,25): error CS0103: The name 'Erc20' does not exist in the current context
> 
> /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(70,30): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(43,29): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(44,65): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(44,80): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(75,19): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(76,21): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(77,65): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(77,82): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(52,28): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(53,64): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(53,79): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(61,28): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(62,64): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(62,79): error CS0103: The name 'Erc20' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(85,30): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(87,61): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(87,78): error CS0103: The name 'Erc1155' does not exist in the current context
> 
> Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(70,28): error CS0103: The name 'Erc20' [...]

2024-05-14 13:02 UTC, oleksandrchainsafe commented
> > I run the setup.sh but Im getting the following build errors:
> > ```
> > Library/PackageCache/com.tools.webglthreadingpatcher@c2f3628a02/ThreadingPatcher/Editor/WebGLThreadingPatcher.cs(21,38): error CS1061: 'BuildReport' does not contain a definition for 'GetFiles' and no accessible extension method 'GetFiles' accepting a first argument of type 'BuildReport' could be found (are you missing a using directive or an assembly reference?)
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(48,28): error CS0103: The name 'Erc721' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(56,26): error CS0103: The name 'Erc721' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(64,31): error CS0103: The name 'Erc721' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc721Tests.cs(72,19): error CS0103: The name 'Erc721' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(30,28): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(38,28): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(49,19): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(139,22): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmTests.cs(110,84): error CS0103: The name 'EthMethod' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(150,23): error CS0103: The name 'Erc721' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(161,24): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(172,29): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(183,30): error CS0103: The name 'Erc721' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmTests.cs(152,34): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/EvmCustomResponseTests.cs(194,31): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc1155Tests.cs(129,23): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(30,28): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(38,34): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(46,27): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(54,23): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(62,25): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/Erc20Tests.cs(70,30): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(43,29): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(44,65): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(44,80): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(75,19): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(76,21): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(77,65): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(77,82): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(52,28): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(53,64): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(53,79): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(61,28): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(62,64): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc20/Erc20Calls.cs(62,79): error CS0103: The name 'Erc20' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(85,30): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(87,61): error CS0103: The name 'Erc1155' does not exist in the current context
> > 
> > Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs(87,78): error CS0103: The name 'Erc1155' does not exist in the curre [...]

2024-05-14 14:48 UTC, kantagara approved these changes

2024-05-15 12:59 UTC, juans-chainsafe requested changes
@oleksandrchainsafe Most of the samples are working, the only one failing is the "ImportNftTexture" with this error:
```
Web3Exception: Metadata request failure: 
Scripts.EVM.Token.Erc1155UnityExtensions.ImportTexture (ChainSafe.Gaming.Evm.Contracts.BuiltIn.Erc1155Contract contract, System.String tokenId) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Erc1155UnityExtensions.cs:24)
Erc1155Calls.ImportNftTexture1155 () (at Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Erc1155/Erc1155Calls.cs:137)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

Is working in dev branch

2024-05-17 07:46 UTC, rob1997 approved these changes

2024-05-17 16:41 UTC, juans-chainsafe approved these changes
-

2024-05-17 16:45 UTC, juans-chainsafe requested changes
https://github.com/ChainSafe/web3.unity/pull/952#pullrequestreview-2057943373

2024-05-20 15:47 UTC, oleksandrchainsafe commented
@juans-chainsafe I don't understand how this works in dev, because the URI of the NFT is not reachable on my end (might be antivirus issue). For token with id "0", i get this URI https://ipfs.chainsafe.io/ipfs/QmfUHuFj3YL2JMZkyXNtGRV8e9aLJgQ6gcSrqbfjWFvbqQ. It is not accessible through a browser on my end. Try it on yours pls.

@sneakzttv Do you know why it works in dev, but when I try to access URI of the same NFT in this branch, it fails? We're accessing the NFT with "0" and contract "0xAA2EbE78aa788d13AfFaaefD38C93333bbC4d51e" right?

2024-05-20 16:04 UTC, sneakzttv commented
> @juans-chainsafe I don't understand how this works in dev, because the URI of the NFT is not reachable on my end (might be antivirus issue). For token with id "0", i get this URI https://ipfs.chainsafe.io/ipfs/QmfUHuFj3YL2JMZkyXNtGRV8e9aLJgQ6gcSrqbfjWFvbqQ. It is not accessible through a browser on my end. Try it on yours pls.
> 
> @sneakzttv Do you know why it works in dev, but when I try to access URI of the same NFT in this branch, it fails? We're accessing the NFT with ID "0" and contract address "0xAA2EbE78aa788d13AfFaaefD38C93333bbC4d51e" right?

Serialized variables im guessing, probably different. That url is down also, which function is it on?

2024-05-20 16:17 UTC, oleksandrchainsafe commented
> Serialized variables im guessing, probably different. That url is down also, which function is it on?

It's `Erc1155.ImportNftTexture1155()`, called from `Erc1155Calls` MonoBehaviour.

2024-05-20 17:32 UTC, sneakzttv commented
works now, congestion perhaps

metadata: https://ipfs.chainsafe.io/ipfs/QmfUHuFj3YL2JMZkyXNtGRV8e9aLJgQ6gcSrqbfjWFvbqQ
image: https://ipfs.chainsafe.io/ipfs/QmSCzzDrn764mXk3RbrYNpNSNn2DTLG4pc9X7XHuhG5y7Q

2024-05-21 03:18 UTC, sneakzttv commented
we're going to have to majorly change the docs again xD

2024-05-21 06:11 UTC, sneakzttv approved these changes

2024-05-21 15:24 UTC, juans-chainsafe approved these changes
URI sample now is working in the editor ✅ 

But when you try to login in a WebGL build it fails:
```
Web3Exception: Resource ChainSafe.Gaming.Resources.erc-20-abi.json not found in the provided assembly.
  at ChainSafe.Gaming.Evm.Utils.AbiHelper.ReadAbiFromResources (System.Reflection.Assembly assembly, System.String resourceName) [0x00000] in <00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---
```

2024-05-21 15:24 UTC, juans-chainsafe requested changes
My bad, I wanted to request changes, not approve

2024-05-21 16:35 UTC, juans-chainsafe commented
> URI sample now is working in the editor ✅
> 
> But when you try to login in a WebGL build it fails:
> 
> ```
> Web3Exception: Resource ChainSafe.Gaming.Resources.erc-20-abi.json not found in the provided assembly.
>   at ChainSafe.Gaming.Evm.Utils.AbiHelper.ReadAbiFromResources (System.Reflection.Assembly assembly, System.String resourceName) [0x00000] in <00000000000000000000000000000000>:0
> --- End of stack trace from previous location where exception was thrown ---
> ```

Created this ticket for this issue https://github.com/ChainSafe/web3.unity/issues/966

2024-05-28 06:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/web3.unity?pullRequest=952) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/web3.unity?pullRequest=952) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: juans-chainsafe<br/>:white_check_mark: creeppak<br/>:white_check_mark: kantagara<br/>:x: =<br/><hr/>**=** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/web3.unity?pullRequest=952) it.</sub>

2024-05-28 07:32 UTC, kantagara commented
@juans-chainsafe should be fixed.

2024-05-28 12:47 UTC, juans-chainsafe requested changes
For some reason the sample "CustomTokenBalance" is not logging anything in the console, I tried a development build as well but I dont see any logs. I remember this was working in the first version that I tested.

I checked with WebGL and editor.

Everything else is working as expected.

2024-05-28 15:06 UTC, juans-chainsafe approved these changes
CustomTokenBalance was removed ✅ 

<img width="750" alt="Screenshot 2024-05-28 at 12 05 56 PM" src="https://github.com/ChainSafe/web3.unity/assets/104365141/e7cee35c-3c9c-40d5-811b-6884d575d4e6">

2024-05-28 19:52 UTC, juans-chainsafe commented
closes #952

2024-05-29 04:45 UTC, merged