Common RPC Abstraction
ChainSafe/web3.unity pull request #967
Opened 2024-05-22 09:36 UTC by rob1997

closes #811

2024-05-22 09:41 UTC, kantagara approved these changes

2024-05-22 11:45 UTC, sneakzttv approved these changes

2024-05-22 12:19 UTC, juans-chainsafe requested changes
Im getting this build error after running setup.sh

`/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Tests/Runtime/StubWalletConnectProvider.cs(6,46): error CS0246: The type or namespace name 'IWalletConnectProvider' could not be found (are you missing a using directive or an assembly reference?)
`

2024-05-22 13:38 UTC, juans-chainsafe approved these changes
Awesome! working in webgl, editor, desktop and iOS builds with the 3 login scenes that we have.

2024-05-23 06:55 UTC, sneakzttv approved these changes

2024-05-23 07:05 UTC, merged